name: e350

channels:
  - conda-forge
dependencies:
  - mamba
  - notebook
  - jupyterhub
  - jupyterlab
  - bokeh
  - conda-lock
  - ghp-import
  - git
  - jupytext
  - jupyter-resource-usage
  - matplotlib=3.4.3
  - numpy=1.21
  - nbgitpuller
  - pandas
  - pip
  - pillow
  - python=3.9
  - discretize
  - empymod
  - ipykernel
  - ipywidgets=7.7.1
  - mkl
  - nb_conda_kernels 
  - pymatsolver
  - qtconsole
  - qtpy
  - scipy
  - scikit-learn
  - discretize=0.8.0
  - SimPEG=0.17.0
  - pip:
    - git+https://github.com/geoscixyz/geosci-labs
